// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v3.20.3
// source: auth.proto

/* eslint-disable */
import { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "auth";

export interface RegisterOtpRequest {
  email: string;
}

export interface RegisterOtpResponse {
  email: string;
  otp: number;
}

export interface VerifyRegisterOtpRequest {
  otp: number;
  email: string;
}

export interface VerifyRegisterOtpResponse {
  slugId: string;
  username: string;
  email: string;
  accessToken: string;
  refreshToken: string;
  sessionId: string;
  role: string;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface LoginResponse {
  accessToken: string;
  refreshToken: string;
  slugId: string;
  username: string;
  email: string;
  sessionId: string;
  role: string;
}

export interface logOutRequest {
  userId: string;
  sessionId: string;
  accessToken: string
}

export interface logOutResponse {
  isSuccess: boolean;
  message: string;
}

export interface RotateTokenRequest {
  userId: string;
  refreshToken: string;
  sessionId: string;
}

export interface RotateTokenResponse {
  accessToken: string;
  refreshToken: string;
  sessionId: string;
}

export interface GetUserTokenQuery {
  userId: string;
}

export interface GetUserTokensResponse {
  tokens: string[];
}

export const AUTH_PACKAGE_NAME = "auth";


export interface GetUserFromSlugRequest {
  slugId: string;
}

export interface GetUserFromSlugResponse {
  userId: string;
  username: string;
  role: string;
  email: string;
}

export interface AuthServiceClient {
  login(request: LoginRequest, metaData: Metadata): Observable<LoginResponse>;

  rotateToken(request: RotateTokenRequest, metaData: Metadata): Observable<RotateTokenResponse>;

  getUserTokens(request: GetUserTokenQuery, metaData: Metadata): Observable<GetUserTokensResponse>;

  registerOtp(request: RegisterOtpRequest, metaData: Metadata): Observable<RegisterOtpResponse>;

  verifyRegisterOtp(request: VerifyRegisterOtpRequest, metaData: Metadata): Observable<VerifyRegisterOtpResponse>;

  getUserFromSlug(request: GetUserFromSlugRequest, metaData: Metadata): Observable<GetUserFromSlugResponse>;

  logOut(request: logOutRequest, metaData: Metadata): Observable<logOutResponse>;
  }

export const AUTH_SERVICE_NAME = "AuthService";
