// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v3.20.3
// source: character.proto

/* eslint-disable */
import { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "character";

export interface CreateCharacterProfileRequest {
  userId: string;
  userName: string;
}

export interface CreateCharacterProfileResponse {
  characterId: string;
  characterName: string;
  characterTitle: string;
  level: number;
  exp: number;
  nextLevelExp: number;
}

export interface GetCharacterProfileRequest {
  userId: string;
}

export interface GetCharacterProfileResponse {
  character: Character | undefined;
}

export interface GetCharacterProfileByBulkRequest {
  userIds: string[];
}

export interface GetCharacterProfileByBulkResponse {
  characters: Character[];
}

export interface Character {
  id: string;
  characterName: string;
  characterTitle: string;
  level: number;
  exp: number;
  nextLevelExp: number;
}

export const CHARACTER_PACKAGE_NAME = "character";

export interface CharacterServiceClient {
  createCharacterProfile(request: CreateCharacterProfileRequest, metaData: Metadata): Observable<CreateCharacterProfileResponse>;

  getCharacterProfile(request: GetCharacterProfileRequest, metaData: Metadata): Observable<GetCharacterProfileResponse>;

  getCharacterProfileByBulk(request: GetCharacterProfileByBulkRequest, metaData: Metadata): Observable<GetCharacterProfileByBulkResponse>;
}

export const CHARACTER_SERVICE_NAME = "CharacterService";
