import { CommonLocalization } from '@shared/interfaces/common';
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v3.20.3
// source: exp.proto

/* eslint-disable */
import { Metadata } from '@grpc/grpc-js';
import { Observable } from 'rxjs';

export const protobufPackage = 'exp';

export interface CreateExpResourceRequest {
  title: CommonLocalization | undefined;
  description: CommonLocalization | undefined;
  type: string;
  maxClaimAccount?: number | undefined;
  maxClaimServer?: number | undefined;
  status: string;
  expAmount: number;
}

export interface CreateExpResourceResponse {
  isSuccess: boolean;
  id: string;
}

export interface UserObject {
  userId: string;
}

export interface ValidateExpResourceRequest {
  resourceId: string;
  id: UserObject | undefined;
}

export interface ValidateExpResourceResponse {
  isValid: boolean;
  errorMessage?: string | undefined;
  expAmount: number;
}

export interface ClaimExpRequest {
  userId: string;
  expAmount: number;
  expResourceId: string;
}

export const EXP_PACKAGE_NAME = 'exp';

export interface ExpServiceClient {
  createExpResource(
    request: CreateExpResourceRequest,
    metaData: Metadata,
  ): Observable<CreateExpResourceResponse>;

  validateExpResource(
    request: ValidateExpResourceRequest,
    metaData: Metadata,
  ): Observable<ValidateExpResourceResponse>;

  claimExp(request: ClaimExpRequest, metaData: Metadata): Observable<void>;
}

export const EXP_SERVICE_NAME = 'ExpService';
